spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # Default to local if not set
  cloud:
    vault:
      uri: http://127.0.0.1:8200  # Vault server URL
      authentication: TOKEN
      token: your-vault-token  # Vault token for authentication
      kv:
        enabled: true
        backend: mysql  # Specify the correct path for your secrets
        default-context: mysql
        profile-separator: '/'
        template: "mysql/{profile}"

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: ${vault.mysql.local.password}  # Fetch password from Vault

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://test-db-host:3306/mydb
    username: test_user
    password: ${vault.mysql.test.password}  # Fetch password from Vault

---
spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://uat-db-host:3306/mydb
    username: uat_user
    password: ${vault.mysql.uat.password}  # Fetch password from Vault

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://prod-db-host:3306/mydb
    username: prod_user
    password: ${vault.mysql.prod.password}  # Fetch password from Vault
